name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v2.0.0
      
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: cristhiankelm
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
          
          
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: cristhian/go_ci_tst:${{ github.ref_name }}
          
